export 'package:dictionary/views/home/home_screen.dart';
export 'package:dictionary/views/home/menu_screen.dart';
export 'package:dictionary/views/home/search_screen.dart';
export 'package:dictionary/views/login/login_screen.dart';
export 'package:dictionary/views/login/signup_screen.dart';
export 'package:dictionary/views/login/splash_screen.dart';
export 'package:dictionary/views/profile/config_screen.dart';
export 'package:dictionary/views/profile/menu_config_screen.dart';
export 'package:dictionary/views/profile/fav_screen.dart';
